### ISSUE TITLE
Add locales support?

### ISSUE THREAD

**Issue by Deniel00** [XxFri3ndlyxX/LegacyFuel#5]
Hi!

I'm using your lasted 'release' version, but i saw you made Jerry Can support. 
I will update on my server, but agian translate it? :D
I'm Hope you made it as soon as.

**Comment by XxFri3ndlyxX** [comment]
You will have to redo your pull request and make sure  to resolve any conflicts. Thanks!

**Comment by Deniel00** [comment]
Reworked locales support, you can check at requests.

**Comment by XxFri3ndlyxX** [comment]
Thanks!
